name: hpc_project
channels:
  - defaults
dependencies:
  - python=3.12
  - pytorch==2.5.1
  - torchvision==0.20.1
  - matplotlib==3.10.8
  - conda-forge::tqdm
  - pyyaml==6.0.2
  - opencv==4.10.0
  - conda-forge::torchinfo
  - ipykernel
  - jupyterlab
  - notebook
  - jupyter
  - conda-forge::pandas
  - conda-forge::pycocotools
  - pyarrow
  - dask
  - conda-forge::wandb
  - pip:
    - graphviz==0.21
    - torchview==0.2.7
prefix: /opt/anaconda3/envs/hpc_project
