name: hpc_project
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - anyio=4.10.0=py312hca03da5_0
  - aom=3.9.1=h7bae524_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py312h254cc4a_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=py312hca03da5_0
  - attrs=25.4.0=py312hca03da5_1
  - babel=2.16.0=py312hca03da5_0
  - beautifulsoup4=4.13.5=py312hca03da5_0
  - blas=1.0=openblas
  - bleach=6.2.0=py312hca03da5_0
  - brotlicffi=1.0.9.2=py312h313beb8_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h191e429_0
  - certifi=2025.10.5=py312hca03da5_0
  - cffi=2.0.0=py312h3a083c1_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py312hca03da5_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.1=py312h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h0121217_3
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.8.16=py312h0962b89_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - eigen=3.4.0=h48ca7d4_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h313beb8_0
  - ffmpeg=4.2.2=h04105a8_0
  - filelock=3.17.0=py312hca03da5_0
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.60.1=py312h254cc4a_0
  - freetype=2.14.1=hce30654_0
  - gettext=0.21.0=hbdbcc25_2
  - giflib=5.2.2=h80987f9_0
  - glib=2.84.4=h863a760_0
  - glib-tools=2.84.4=hff4a405_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py312h5c1b81f_0
  - gnutls=3.6.15=h887c41c_0
  - graphite2=1.3.14=hc377ac9_1
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - h11=0.16.0=py312hca03da5_1
  - harfbuzz=4.3.0=he9eebac_2
  - hdf5=1.12.1=h05c076b_3
  - httpcore=1.0.9=py312hca03da5_0
  - httpx=0.28.1=py312hca03da5_1
  - icu=73.1=h313beb8_0
  - idna=3.7=py312hca03da5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=py312hca03da5_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py312hca03da5_0
  - jpeg=9f=h2f69dba_0
  - json5=0.9.25=py312hca03da5_0
  - jsonschema=4.25.0=py312hca03da5_0
  - jsonschema-specifications=2023.7.1=py312hca03da5_0
  - jupyter=1.1.1=py312hca03da5_0
  - jupyter-lsp=2.2.5=py312hca03da5_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=py312hca03da5_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=py312hca03da5_0
  - jupyter_server=2.16.0=py312hca03da5_0
  - jupyter_server_terminals=0.5.3=py312hca03da5_0
  - jupyterlab=4.4.7=py312hca03da5_0
  - jupyterlab_pygments=0.3.0=py312hca03da5_0
  - jupyterlab_server=2.28.0=py312hca03da5_0
  - jupyterlab_widgets=3.0.15=py312hca03da5_0
  - kiwisolver=1.4.8=py312h313beb8_0
  - krb5=1.20.1=hf3e1bf2_1
  - lame=3.100=h1a28f6b_0
  - lcms2=2.16=he93ba84_0
  - lerc=4.0.0=h313beb8_0
  - libabseil=20240116.2=cxx17_h313beb8_0
  - libavif=1.3.0=hb06b76e_2
  - libavif16=1.3.0=hb06b76e_2
  - libclang=14.0.6=default_h1b80db6_2
  - libclang13=14.0.6=default_h24352ff_2
  - libcurl=8.16.0=h01d3526_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h02f6b3c_1
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=5.0.0=14_2_0_h6c33f7e_103
  - libgfortran5=14.2.0=h6c33f7e_103
  - libglib=2.84.4=h7a3292d_0
  - libiconv=1.16=h80987f9_3
  - libidn2=2.3.4=h80987f9_0
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - libkrb5=1.21.3=h73ed823_4
  - libllvm14=14.0.6=h19fdd8a_4
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.30=hf2bb037_0
  - libopenjpeg=2.5.4=haa24f5a_0
  - libopus=1.3.1=h80987f9_1
  - libpng=1.6.50=h5c318fc_0
  - libpq=17.6=h479fd88_0
  - libprotobuf=4.25.3=h514c7bf_0
  - libsodium=1.0.20=h897f8a9_0
  - libsqlite=3.50.4=hf8de324_0
  - libssh2=1.11.1=h3e2b118_0
  - libtasn1=4.20.0=h25138cc_0
  - libtiff=4.5.1=hc9ead59_1
  - libunistring=0.9.10=h1a28f6b_0
  - libvpx=1.10.0=hc377ac9_0
  - libwebp=1.3.2=ha3663a8_0
  - libwebp-base=1.3.2=h80987f9_1
  - libxcb=1.17.0=h3fc13f7_0
  - libxml2=2.13.8=h0b34f26_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lmdb=0.9.31=h79febb2_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py312h80987f9_0
  - matplotlib=3.10.6=py312hca03da5_0
  - matplotlib-base=3.10.6=py312h066045a_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.1.2=py312hca03da5_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py312hca03da5_0
  - mysql=8.4.0=h3a6587f_1
  - nbclient=0.10.2=py312hca03da5_0
  - nbconvert=7.16.6=py312hca03da5_0
  - nbconvert-core=7.16.6=py312hca03da5_0
  - nbconvert-pandoc=7.16.6=py312hca03da5_0
  - nbformat=5.10.4=py312hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.7.3=h84b5d62_1
  - networkx=3.5=py312hca03da5_0
  - notebook=7.4.5=py312hca03da5_0
  - notebook-shim=0.2.4=py312hca03da5_0
  - numpy=1.26.4=py312h901140f_1
  - numpy-base=1.26.4=py312hae06d03_1
  - opencv=4.10.0=py312h266819b_0
  - openh264=1.8.0=h98b2900_0
  - openjpeg=2.5.2=h54b8e55_0
  - openldap=2.6.10=h6d5b105_1
  - openssl=3.5.4=h5503f6c_0
  - overrides=7.4.0=py312hca03da5_0
  - packaging=25.0=py312hca03da5_1
  - pandas=2.3.3=py312h5978115_1
  - pandoc=2.12=hca03da5_3
  - pandocfilters=1.5.1=py312hca03da5_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h1dacb4a_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py312h84e58ab_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h09dc60e_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prometheus_client=0.21.1=py312hca03da5_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py312haa24f5a_1
  - pthread-stubs=0.3=h1a28f6b_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycocotools=2.0.10=py312ha11c99a_1
  - pycparser=2.23=py312hca03da5_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.0=py312hca03da5_0
  - pysocks=1.7.1=py312hca03da5_0
  - python=3.12.12=h18782d2_1_cpython
  - python-dateutil=2.9.0post0=py312hca03da5_2
  - python-fastjsonschema=2.20.0=py312hca03da5_0
  - python-json-logger=3.2.1=py312hca03da5_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.12=1_cp312
  - pytorch=2.5.1=py3.12_0
  - pytz=2025.2=py312hca03da5_0
  - pyyaml=6.0.2=py312h80987f9_0
  - pyzmq=27.1.0=py312h854a7ef_0
  - qhull=2020.2=h48ca7d4_2
  - qt-main=5.15.2=h0917680_12
  - qtconsole=5.7.0=py312hca03da5_0
  - qtpy=2.4.3=py312hca03da5_0
  - rav1e=0.7.1=h0716509_3
  - readline=8.3=h0b18652_0
  - referencing=0.30.2=py312hca03da5_0
  - requests=2.32.5=py312hca03da5_0
  - rfc3339-validator=0.1.4=py312hca03da5_0
  - rfc3986-validator=0.1.1=py312hca03da5_0
  - rpds-py=0.22.3=py312h2aea54e_0
  - send2trash=1.8.2=py312hca03da5_1
  - setuptools=80.9.0=py312hca03da5_0
  - six=1.17.0=py312hca03da5_0
  - sniffio=1.3.0=py312hca03da5_0
  - soupsieve=2.5=py312hca03da5_0
  - sqlite=3.50.4=h6e44f1d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=3.1.2=h12ba402_0
  - sympy=1.14.0=py312hca03da5_0
  - terminado=0.18.1=py312hca03da5_0
  - tinycss2=1.4.0=py312hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - torchinfo=1.8.0=pyhd8ed1ab_1
  - torchvision=0.20.1=py312_cpu
  - tornado=6.5.1=py312h80987f9_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=py312hca03da5_0
  - typing_extensions=4.15.0=py312hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py312hca03da5_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webencodings=0.5.1=py312hca03da5_2
  - websocket-client=1.8.0=py312hca03da5_0
  - wheel=0.45.1=py312hca03da5_0
  - widgetsnbextension=4.0.14=py312hca03da5_0
  - x264=1!152.20180806=h1a28f6b_0
  - xorg-libxau=1.0.12=h3fc13f7_0
  - xorg-libxdmcp=1.1.5=h3fc13f7_0
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h2c7f8f0_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h5f15de7_0
  - zlib-ng=2.2.5=hf787086_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - albucore==0.0.33
      - annotated-types==0.7.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - scipy==1.16.3
      - simsimd==6.5.3
      - stringzilla==4.2.3
      - typing-inspection==0.4.2
prefix: /opt/anaconda3/envs/hpc_project
