name: hpc_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - jupyter
  - opencv==4.10.0
  - pytorch::pytorch==2.5.1
  - dask
  - pyarrow
  - conda-forge::matplotlib
  - conda-forge::pycocotools
prefix: /home/cuda/anaconda3/envs/hpc_project
